apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice-deployment
spec:
  selector:
    matchLabels:
      app: invoiceservice
  replicas: 1
  template:
    metadata:
      labels:
        app: invoiceservice
    spec:
      containers:
        - name: invoiceservice
          image: emreoytun/invoiceservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082  # Updated to match the application's port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: invoiceservice-ssvc
spec:
  selector:
    app: invoiceservice
  ports:
    - protocol: "TCP"
      port: 80             # Port exposed by the service
      targetPort: 8082     # Port on which the application is listening
  type: LoadBalancer
